package de.bbht.development.connector.todo.entity;

public enum ToDoOperation {

  LIST_TASK_LISTS, GET_TASK_LIST, CREATE_TASK_LIST, UPDATE_TASK_LIST, DELETE_TASK_LIST, LIST_TASKS, GET_TASK, CREATE_TASK, UPDATE_TASK, DELETE_TASK, LIST_CHECK_LIST_ITEMS, GET_CHECK_LIST_ITEM, CREATE_CHECK_LIST_ITEM, UPDATE_CHECK_LIST_ITEM, DELETE_CHECK_LIST_ITEM

}
